fix build error with clang and gcc " (#2742)
This very minor, trivial and risk free commit fix introduced in 8.12.45 with #2734
error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wunused-result]"
Without this fix, I cannot build using clang++13