Fix javascript build issues (#2425)
Compiling errors found when compiled against new version of closure-compiler
>> No warning class for name: ambiguousFunctionDecl
>> Same case for:
fileoverviewTags google/closure-compiler@04cba67
internetExplorerChecks google/closure-compiler@baab835
>> Moreover, deprecated syntax errors for defineClass
"[exec] /Users/lee/ClickToCloud/git/closure-library/closure/goog/base.js:2259: ERROR - [JSC_DEPRECATED_PROP_REASON]"

So we have updated the build.xml so that it no more considers these specific issues as errors and block the build/compilation.